import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import orangeGuy from '../images/orangeJacket.svg';
import Card from '../components/Card';
export default function Home() {
	return (
		<div>
			<div className="bg-[#A2DAF8] rounded-r-3xl pt-10 mr-16">
				<Head>
					<title>Adam Andrews</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
					<link
						href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Righteous&display=swap"
						rel="stylesheet"
					/>
				</Head>
				<div>
					<Header />
					<div className="px-5  py-10 sm:grid md:grid-cols-2 3xl:flex flex-wrap justifty-center">
						<div className="p-2 font-['Righteous']">
							<p className="text-5xl">Hi i’m Adam</p>
							<p className=" pt-5 text-3xl">
								A freelance web developer based in the uk
							</p>
						</div>
						<div className="p-2">
							<Image
								src={orangeGuy}
								layout="responsive"
								height={1080}
								width={1920}
							/>
						</div>
					</div>
				</div>
			</div>
			<section>
			<div className="p-2 flex justify-center items-center align-center font-['Righteous']">
							<h1 className="text-5xl">My projects</h1>
						</div>
			<div className="bg-gray-800 px-5  py-10 sm:grid md:grid-cols-2 3xl:flex flex-wrap justifty-center">
						<Card/>
						<Card/>
					</div>
			</section>
		</div>
	);
}
