import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import orangeGuy from '../images/orangeJacket.svg';
export default function Home() {
	return (
		<div className="bg-[#A2DAF8] rounded-r-3xl pt-10 mr-16">
			<Head>
				<title>Adam-Andrews</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <div>
      <Header />
			<div className=" px-5  sm:grid md:grid-cols-2 3xl:flex flex-wrap justift-center mr-16 	">
				<div className="p-2 group cursor-pointer transition duration-200 ease-in transform sm:hover:scale-x-105 hover:z-50">
					<p className="text-8xl">Hi i’m Adam 
          A freelance web developer based in the uk
          </p>
				</div>
				<div className="p-2 group cursor-pointer transition duration-200 ease-in transform sm:hover:scale-x-105 hover:z-50">
					<Image
						src={orangeGuy}
						layout="responsive"
						height={1080}
						width={1920}
					/>
				</div>
			</div>
			<section className="container bg-slate-900"></section>
      </div>
		</div>
	);
}
