import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Adam-Andrews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <navbar className ="flex justify-end my-8">
        <div className="flex mx-20 justify-evenly max-w-2xl font-medium items-center">
        <h1 className="px-4">Home</h1>
        <h1 className="px-4">About us</h1>
        <button className="rounded-md px-4 py-1 border border-white"> 
        <h1>Contact</h1>
        </button>
        </div>
      </navbar>
    </div>
  )
}
